- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic_https:
        elastic_host: "{{ elk_host }}"
        elastic_port: "{{ elk_port }}"
        elastic_username: "{{ elk_username }}"
        elastic_password: "{{ elk_password }}"
        elastic_index_pattern: logs-*
        query: |
          term:
            cisco_meraki.event_type: urls
        interval: 20

  rules:
    - name: Debug event
      condition: event.ecs is defined and event.subtype == "http_access_error"
      action:
        debug:
