- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic:
        host: https://elk-stack1.integ.conres.com
        port: 9200
        username: elastic
        password: 'p3WnX6S56WDtb6=wf30Y'
        index_pattern: filebeat-*
        query: |
          term:
            container.name.keyword: nginx
        interval: 5

  rules:
    - name: Debug event
      condition: event.ecs is defined and event.nginx.log_level == "error"
      action:
        debug:
