- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic_https:
        elastic_host: "{{ elk_host }}"
        elastic_port: "{{ elk_port }}"
        elastic_username: "{{ elk_username }}"
        elastic_password: "{{ elk_password }}"
        elastic_index_pattern: logs-*
        query: |
          term:
            observer.hostname: NH_PS_Integ_FW_1 
        interval: 20

  rules:
    - name: Debug event
      condition: event.ecs is defined and cisco_meraki.event_subtype == "http_access_error"
      action:
        debug:
