- name: Elastic events
  hosts: localhost
  sources:
    - cloin.eda.elastic_https:
        elastic_host: "{{ elk_host }}"
        elastic_port: "{{ elk_port }}"
        elastic_username: "{{ elk_username }}"
        elastic_password: "{{ elk_password }}"
        elastic_index_pattern: logs-*
        query: |
          bool:
            must:
              - term:
                  cisco_meraki.event_type.keyword: urls
              - term:
                  event.event_subtype.keyword: http_access_error
        interval: 20

  rules:
    - name: Debug event
      condition: event.ecs is defined
      action:
        debug:
