download_url: https://galaxy.ansible.com/api/v3/plugin/ansible/content/published/collections/artifacts/cloin-eda-2.1.15.tar.gz
format_version: 1.0.0
name: eda
namespace: cloin
server: https://galaxy.ansible.com/api/
signatures: []
version: 2.1.15
version_url: /api/v3/plugin/ansible/content/published/collections/index/cloin/eda/versions/2.1.15/
